platform:ios, ‘9.0’

use_frameworks!

target 'AcrossAnHui' do

    pod 'AFNetworking'
    pod 'Masonry'
    pod 'MJRefresh'
    pod 'MBProgressHUD'
    pod 'YYKit'

    pod 'AMapNavi'#导航SDK,已包含3D地图，无需单独引入3D地图
    pod 'AMapSearch'#地图SDK搜索功能
    pod 'AMapLocation'#定位SDK
    
    pod 'UICountingLabel'#图表

    pod ‘JPush’#极光推送
    
    pod 'UMengAnalytics'
    # U-Share SDK UI模块（分享面板，建议添加）
    pod ‘UMengUShare/UI’
    # 集成微信(精简版0.2M)
    pod ‘UMengUShare/Social/ReducedWeChat'
    # 集成QQ(精简版0.5M)
    pod ‘UMengUShare/Social/ReducedQQ'

end
